import { fetchData } from '@/common/api';
import Pagination from '@/components/pagination/paginateion';
import { BlogPost } from '@/mokData/dataList';
import Head from 'next/head';
import { useEffect, useId, useState } from 'react';

interface IResponseLists {
  total: number;
  bloglistData: BlogPost[];
}

export default function Home() {
  const [lists, setLists] = useState<IResponseLists>({
    total: 0,
    bloglistData: [],
  });

  const [currentPage, setCurrentPage] = useState(1);
  const prefix = useId();

  useEffect(() => {
    fetchData(setLists, currentPage);
  }, [currentPage]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>블로그 리스트 입니다</h1>
        <ul>
          {lists?.bloglistData.map((item, index) => (
            <li key={prefix + index}>
              <h2>{item.title}</h2>
              <p>{item.body}</p>
            </li>
          ))}
        </ul>
        <Pagination
          totalItems={lists.total}
          itemsPerPage={10}
          setCurrentPage={setCurrentPage}
          currentPage={currentPage}
        />
      </main>
    </>
  );
}
