import { fetchData } from '@/common/api';
import { BlogPost } from '@/mokData/dataList';
import Head from 'next/head';
import { useEffect, useId, useState } from 'react';

export default function Home() {
  const [lists, setLists] = useState<BlogPost[]>([]);
  const prefix = useId();

  useEffect(() => {
    fetchData(setLists);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>블로그 리스트 입니다</h1>
        <ol>
          {lists.map((item, index) => (
            <li key={prefix + index}>
              <h2>{item.title}</h2>
              <p>{item.body}</p>
            </li>
          ))}
        </ol>
      </main>
    </>
  );
}
